"""Add language column to messages

Revision ID: 949748db67be
Revises: 001_initial
Create Date: 2026-09-13 19:12:45.164531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '949748db67be'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_action_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('action_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_meta'
    )
    op.create_index(op.f('ix_agent_meta_agent_action_logs_session_id'), 'agent_action_logs', ['session_id'], unique=False, schema='agent_meta')
    op.create_table('chat_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('agent_response', sa.Text(), nullable=False),
    sa.Column('detected_intent', sa.String(length=32), nullable=True),
    sa.Column('detected_language', sa.String(length=16), nullable=True),
    sa.Column('tools_called', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_results_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('response_latency_ms', sa.Float(), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=True),
    sa.Column('customer_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='agent_meta'
    )
    op.create_index(op.f('ix_agent_meta_chat_interactions_customer_id'), 'chat_interactions', ['customer_id'], unique=False, schema='agent_meta')
    op.create_index(op.f('ix_agent_meta_chat_interactions_session_id'), 'chat_interactions', ['session_id'], unique=False, schema='agent_meta')
    op.create_index(op.f('ix_agent_meta_conversations_customer_id'), 'conversations', ['customer_id'], unique=False, schema='agent_meta')
    op.create_index(op.f('ix_agent_meta_customer_context_cache_customer_id'), 'customer_context_cache', ['customer_id'], unique=False, schema='agent_meta')
    op.add_column('messages', sa.Column('language', sa.String(length=16), nullable=True), schema='agent_meta')
    op.create_index(op.f('ix_agent_meta_messages_session_id'), 'messages', ['session_id'], unique=False, schema='agent_meta')
    op.create_index(op.f('ix_agent_meta_tool_invocations_session_id'), 'tool_invocations', ['session_id'], unique=False, schema='agent_meta')
    op.alter_column('part_fitment', 'part_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               schema='catalog')
    op.drop_index(op.f('ix_fitment_vehicle'), table_name='part_fitment', schema='catalog')
    op.create_index(op.f('ix_catalog_part_fitment_fuel_type'), 'part_fitment', ['fuel_type'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_part_fitment_vehicle_make'), 'part_fitment', ['vehicle_make'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_part_fitment_vehicle_model'), 'part_fitment', ['vehicle_model'], unique=False, schema='catalog')
    op.alter_column('part_interchanges', 'part_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               schema='catalog')
    op.alter_column('part_interchanges', 'alternate_part_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               schema='catalog')
    op.drop_index(op.f('ix_parts_oem'), table_name='parts', schema='catalog')
    op.drop_index(op.f('ix_parts_sku'), table_name='parts', schema='catalog')
    op.create_index(op.f('ix_catalog_parts_oem_part_number'), 'parts', ['oem_part_number'], unique=False, schema='catalog')
    op.create_index(op.f('ix_catalog_parts_sku'), 'parts', ['sku'], unique=False, schema='catalog')
    op.create_index(op.f('ix_governance_guardrail_events_session_id'), 'guardrail_events', ['session_id'], unique=False, schema='governance')
    op.create_index(op.f('ix_governance_prompt_versions_prompt_key'), 'prompt_versions', ['prompt_key'], unique=False, schema='governance')
    op.create_index(op.f('ix_marketplace_garage_capabilities_garage_id'), 'garage_capabilities', ['garage_id'], unique=False, schema='marketplace')
    op.alter_column('garages', 'garage_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False,
               schema='marketplace')
    op.create_index(op.f('ix_operations_claims_vehicle_reg_no'), 'claims', ['vehicle_reg_no'], unique=False, schema='operations')
    op.create_index(op.f('ix_operations_policy_rules_vehicle_reg_no'), 'policy_rules', ['vehicle_reg_no'], unique=False, schema='operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_policy_rules_vehicle_reg_no'), table_name='policy_rules', schema='operations')
    op.drop_index(op.f('ix_operations_claims_vehicle_reg_no'), table_name='claims', schema='operations')
    op.alter_column('garages', 'garage_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True,
               schema='marketplace')
    op.drop_index(op.f('ix_marketplace_garage_capabilities_garage_id'), table_name='garage_capabilities', schema='marketplace')
    op.drop_index(op.f('ix_governance_prompt_versions_prompt_key'), table_name='prompt_versions', schema='governance')
    op.drop_index(op.f('ix_governance_guardrail_events_session_id'), table_name='guardrail_events', schema='governance')
    op.drop_index(op.f('ix_catalog_parts_sku'), table_name='parts', schema='catalog')
    op.drop_index(op.f('ix_catalog_parts_oem_part_number'), table_name='parts', schema='catalog')
    op.create_index(op.f('ix_parts_sku'), 'parts', ['sku'], unique=False, schema='catalog')
    op.create_index(op.f('ix_parts_oem'), 'parts', ['oem_part_number'], unique=False, schema='catalog')
    op.alter_column('part_interchanges', 'alternate_part_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               schema='catalog')
    op.alter_column('part_interchanges', 'part_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               schema='catalog')
    op.drop_index(op.f('ix_catalog_part_fitment_vehicle_model'), table_name='part_fitment', schema='catalog')
    op.drop_index(op.f('ix_catalog_part_fitment_vehicle_make'), table_name='part_fitment', schema='catalog')
    op.drop_index(op.f('ix_catalog_part_fitment_fuel_type'), table_name='part_fitment', schema='catalog')
    op.create_index(op.f('ix_fitment_vehicle'), 'part_fitment', ['vehicle_make', 'vehicle_model', 'fuel_type'], unique=False, schema='catalog')
    op.alter_column('part_fitment', 'part_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               schema='catalog')
    op.drop_index(op.f('ix_agent_meta_tool_invocations_session_id'), table_name='tool_invocations', schema='agent_meta')
    op.drop_index(op.f('ix_agent_meta_messages_session_id'), table_name='messages', schema='agent_meta')
    op.drop_column('messages', 'language', schema='agent_meta')
    op.drop_index(op.f('ix_agent_meta_customer_context_cache_customer_id'), table_name='customer_context_cache', schema='agent_meta')
    op.drop_index(op.f('ix_agent_meta_conversations_customer_id'), table_name='conversations', schema='agent_meta')
    op.drop_index(op.f('ix_agent_meta_chat_interactions_session_id'), table_name='chat_interactions', schema='agent_meta')
    op.drop_index(op.f('ix_agent_meta_chat_interactions_customer_id'), table_name='chat_interactions', schema='agent_meta')
    op.drop_table('chat_interactions', schema='agent_meta')
    op.drop_index(op.f('ix_agent_meta_agent_action_logs_session_id'), table_name='agent_action_logs', schema='agent_meta')
    op.drop_table('agent_action_logs', schema='agent_meta')
    # ### end Alembic commands ###
